stages:
  query:
    wdir: ../../
    cmd: >-
      python -m src.query
      ${bounds}
      --filename ${filename}
    outs:
      - ./data/raw/${filename}.gpkg
  clean:
    wdir: ../../
    deps:
      - ./data/raw/${filename}.gpkg
    cmd: >-
      python -m src.clean
      --filename ${filename}
    outs:
      - ./data/processed/${filename}.parquet
